ME-507 Term Project: Ball Fetching Car: task_radio Class Reference
task_radio Class Reference
This task is used to control the RF transciever.
#include <task_radio.h>
Public Member Functions
task_radio (const char *, unsigned portBASE_TYPE, size_t, emstream *)
void run (void)
Protected Member Functions
void init_spi (void)
A method to initialize the SPI interface to the RF module.
char write_byte (char)
A method to send a byte to the RF module.
uint8_t get_reg (uint8_t)
A method to get the value of a register on the RF module.
uint8_t * read_or_write (uint8_t, uint8_t, uint8_t *, uint8_t)
A method to write data to the RF module.
void transmit (uint8_t *)
A method to transmit a character array with the RF module.
Detailed Description
This task is used to control the RF transciever.
This task inherits the TaskBase class, and is used to run as a finite state machine. It controls the actions of the RF transciever using an SPI interface. While this task can communicate with the RF transciever, we have not gotten the transciever to communicate with another RF module.
Definition at line 61 of file task_radio.h.
Constructor & Destructor Documentation
task_radio()
task_radio::task_radio (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
This constructor creates a new data acquisition task. Its main job is to call the parent class's constructor which does most of the work.
Parameters
a_name A character string which will be the name of this task
a_priority The priority at which this task will initially run (default: 0)
a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev A pointer to the serial port which writes debugging info.
Definition at line 48 of file task_radio.cpp.
Member Function Documentation
get_reg()
uint8_t task_radio::get_reg (uint8_t reg) protected
A method to get the value of a register on the RF module.
This method uses the SPI data register on our microcontroller to send a byte of information to the RF module.
Parameters
reg A uint8_t value that corresonds to the desired register.
Returns
reg The uint8_t data that was contained in the desired register RF module.
Definition at line 201 of file task_radio.cpp.
References write_byte().
Referenced by run().
init_spi()
void task_radio::init_spi (void) protected
A method to initialize the SPI interface to the RF module.
This method sets the correct SPI pins as inputs and outputs, and sets their states so that the SPI interface can connect to the RF module.
Definition at line 159 of file task_radio.cpp.
Referenced by run().
read_or_write()
uint8_t * task_radio::read_or_write (uint8_t ReadWrite, uint8_t reg, uint8_t * val, uint8_t antVal) protected
A method to write data to the RF module.
This method uses the SPI data register on our microcontroller to send a byte of information to the RF module.
Parameters
ReadWrite A uint8_t character that corresponds to either a value being written to or read from the RF module.
reg A uint8_t value that corresponds to the register of the RF module that is being modified.
val A pointer to the values array that are to written to the RF module.
antVal A uint8_t value that signifies the number of bytes to write to the RF module.
Returns
ret The array of uint8_t* data that was sent to the RF module.
Definition at line 231 of file task_radio.cpp.
References write_byte().
Referenced by run(), and transmit().
run()
void task_radio::run (void)
This method is called by the RTOS once to run the task loop for ever and ever.
This task handles sending messages over the transciever to the transponder
Definition at line 64 of file task_radio.cpp.
References get_reg(), init_spi(), p_rf_ping, read_or_write(), and transmit().
transmit()
void task_radio::transmit (uint8_t * W_buff) protected
A method to transmit a character array with the RF module.
This method uses the read_or_write method to transmit an array of characters using the RF module.
Parameters
W_buff A uint8_t* pointer to an array which is to be sent to the RF module.
Definition at line 273 of file task_radio.cpp.
References read_or_write().
Referenced by run().
write_byte()
char task_radio::write_byte (char c_data) protected
A method to send a byte to the RF module.
This method uses the SPI data register on our microcontroller to send a byte of information to the RF module.
Parameters
c_data A char byte that is to be sent to the RF module.
Returns
SPDR The char data that was sent to the RF module.
Definition at line 183 of file task_radio.cpp.
Referenced by get_reg(), and read_or_write().
The documentation for this class was generated from the following files:
task_radio.h
task_radio.cpp